import i18n from "../i18n";

export const questions = {
  history: {
    gutenberg: [
      { question: i18n.t("gh1"), answer: true },
      { question: i18n.t("gh2"), answer: true },
      { question: i18n.t("gh3"), answer: true },
      { question: i18n.t("gh4"), answer: false },
      { question: i18n.t("gh5"), answer: true },
      { question: i18n.t("gh6"), answer: true },
      { question: i18n.t("gh7"), answer: true },
      { question: i18n.t("gh8"), answer: true },
      { question: i18n.t("gh9"), answer: true },
      { question: i18n.t("gh10"), answer: true },
      { question: i18n.t("gh11"), answer: true },
      { question: i18n.t("gh12"), answer: false },
      { question: i18n.t("gh13"), answer: true },
      { question: i18n.t("gh14"), answer: true },
      { question: i18n.t("gh15"), answer: true },
    ],
    broadcasting: [
      { question: i18n.t("bh1"), answer: true },
      { question: i18n.t("bh2"), answer: true },
      { question: i18n.t("bh3"), answer: true },
      { question: i18n.t("bh4"), answer: false },
      { question: i18n.t("bh5"), answer: true },
      { question: i18n.t("bh6"), answer: false },
      { question: i18n.t("bh7"), answer: true },
      { question: i18n.t("bh8"), answer: true },
      { question: i18n.t("bh9"), answer: true },
      { question: i18n.t("bh10"), answer: true },
      { question: i18n.t("bh11"), answer: true },
      { question: i18n.t("bh12"), answer: true },
      { question: i18n.t("bh13"), answer: true },
      { question: i18n.t("bh14"), answer: true },
      { question: i18n.t("bh15"), answer: true },
    ],
    digital: [
      { question: i18n.t("dh1"), answer: false },
      { question: i18n.t("dh2"), answer: true },
      { question: i18n.t("dh3"), answer: true },
      { question: i18n.t("dh4"), answer: false },
      { question: i18n.t("dh5"), answer: true },
      { question: i18n.t("dh6"), answer: true },
      { question: i18n.t("dh7"), answer: false },
      { question: i18n.t("dh8"), answer: true },
      { question: i18n.t("dh9"), answer: false },
      { question: i18n.t("dh10"), answer: true },
      { question: i18n.t("dh11"), answer: false },
      { question: i18n.t("dh12"), answer: true },
      { question: i18n.t("dh13"), answer: false },
      { question: i18n.t("dh14"), answer: true },
      { question: i18n.t("dh15"), answer: true },
    ],
  },
  content: {
    gutenberg: [
      { question: i18n.t("gc1"), answer: false },
      { question: i18n.t("gc2"), answer: false },
      { question: i18n.t("gc3"), answer: false },
      { question: i18n.t("gc4"), answer: true },
      { question: i18n.t("gc5"), answer: true },
      { question: i18n.t("gc6"), answer: true },
      { question: i18n.t("gc7"), answer: false },
      { question: i18n.t("gc8"), answer: false },
      { question: i18n.t("gc9"), answer: true },
      { question: i18n.t("gc10"), answer: false },
      { question: i18n.t("gc11"), answer: true },
      { question: i18n.t("gc12"), answer: true },
      { question: i18n.t("gc13"), answer: false },
      { question: i18n.t("gc14"), answer: true },
      { question: i18n.t("gc15"), answer: true },
    ],
    broadcasting: [
      { question: i18n.t("bc1"), answer: true },
      { question: i18n.t("bc2"), answer: false },
      { question: i18n.t("bc3"), answer: false },
      { question: i18n.t("bc4"), answer: true },
      { question: i18n.t("bc5"), answer: false },
      { question: i18n.t("bc6"), answer: true },
      { question: i18n.t("bc7"), answer: true },
      { question: i18n.t("bc8"), answer: true },
      { question: i18n.t("bc9"), answer: true },
      { question: i18n.t("bc10"), answer: true },
      { question: i18n.t("bc11"), answer: true },
      { question: i18n.t("bc12"), answer: false },
      { question: i18n.t("bc13"), answer: true },
      { question: i18n.t("bc14"), answer: true },
      { question: i18n.t("bc15"), answer: false },
    ],
    digital: [
      { question: i18n.t("dc1"), answer: true },
      { question: i18n.t("dc2"), answer: false },
      { question: i18n.t("dc3"), answer: true },
      { question: i18n.t("dc4"), answer: true },
      { question: i18n.t("dc5"), answer: true },
      { question: i18n.t("dc6"), answer: true },
      { question: i18n.t("dc7"), answer: true },
      { question: i18n.t("dc8"), answer: true },
      { question: i18n.t("dc9"), answer: false },
      { question: i18n.t("dc10"), answer: true },
      { question: i18n.t("dc11"), answer: true },
      { question: i18n.t("dc12"), answer: true },
      { question: i18n.t("dc13"), answer: false },
      { question: i18n.t("dc14"), answer: true },
      { question: i18n.t("dc15"), answer: true },
    ],
  },
};
